In [6]:
def quicksort(arr):
    if (len(arr) <= 1):
        return arr
    
    pivot = arr[int(len(arr) /  2)]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    
    return quicksort(left) + middle + quicksort(right)

In [7]:
arr = [3, 7, 39, 10, 12, 87, 23, 12]
print(quicksort(arr))

[3, 7, 10, 12, 12, 23, 39, 87]


In [8]:
import numpy as np


In [12]:
# generating a np array
a = np.zeros((2,2))
print(a)
b = np.ones((1,2))
print(b)
c = np.full((2,2),7)
print(c)
d = np.eye(2)
print(d)
e = np.random.random((2,2))
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.66801985 0.77784172]
 [0.90706439 0.06198227]]


In [17]:
# array indexing
a = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
b = a[:2, 1:3]
print(b)
print(a[0,1])
b[0,0] = 77 # it will change a too!!!
print(a)
row_r1 = a[1, :]
row_r2 = a[1:2, :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

[[2 3]
 [6 7]]
2
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [19]:
# boolean array indexing
a = np.array([[1,2],[3,4],[5,6]])
bool_idx = (a > 2)
print(bool_idx)
print(a[bool_idx])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


### Broadcasting:
##### If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length
##### The two arrays are said to be compatitble in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimensions
##### The arrays can be broadcast together if they are compatible in all dimensions.
##### After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
##### In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

In [21]:
# Broadcasting
x = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
v = np.array([1,0,1,1])
y = x + v # notice that v extends to (4,4) array
print(y) 

[[ 2  2  4  5]
 [ 6  6  8  9]
 [10 10 12 13]]
