In [19]:
import numpy as np
from scipy import linalg as LA
import matplotlib.pyplot as plt

In [4]:
A = np.array([[4,3],[2,2],[-1,-3], [-5, -2]])
U, s, Vt = LA.svd(A, full_matrices=False)
U, s, Vt

(array([[-0.61215255, -0.05228813],
        [-0.34162337, -0.2025832 ],
        [ 0.31300005,  0.80704816],
        [ 0.64077586, -0.55217683]]),
 array([8.16552039, 2.30743942]),
 array([[-0.81424526, -0.58052102],
        [ 0.58052102, -0.81424526]]))

In [5]:
x = np.array([0.243,0.97])
x = x/LA.norm(x)

xi= Vt.dot(x)
xi

array([-0.7609864 , -0.64876784])

In [6]:
S = LA.diagsvd(s, 2,2)
eta = S.dot(xi)
eta

array([-6.21384993, -1.49699248])

In [8]:
LA.norm(eta)

6.391628704703711

In [9]:
y = U.dot(eta)
y

array([ 3.88209899,  2.42606187, -3.1530804 , -3.15508046])

In [10]:
A.dot(x)

array([ 3.88209899,  2.42606187, -3.1530804 , -3.15508046])

In [17]:
U.T.dot(U)

array([[ 1.00000000e+00, -2.36122849e-17],
       [-2.36122849e-17,  1.00000000e+00]])

In [22]:
x1 = np.array([2, 3])
x2 = np.array([3,4])
x3 = x1.dot(x2)
x3 

AttributeError: module 'numpy' has no attribute 'norm'

In [82]:
"""
get eigenvalue and eigenvector using powerMethod, notice M should be normalized
"""
def powerMethod(M, q):
    n = M[0,:]
    for i in range(q):
        n = M.dot(n)
    return n / np.linalg.norm(n)


In [83]:
M=np.array([[2,3,4],[5,6,7],[8,9,10]])
M = M / np.linalg.norm(M)
u = powerMethod(M, 10)
u

array([0.28263801, 0.5382937 , 0.7939494 ])

In [88]:
l = M.dot(u)[0]/u[0]
l

0.9670317270615643

In [87]:
M.dot(u)

array([0.27331992, 0.52054709, 0.76777426])

In [89]:
"""
MU = lU
"""
l*u

array([0.27331992, 0.52054709, 0.76777426])

In [91]:
M.dot(u)/np.linalg.norm(M.dot(u))

array([0.28263801, 0.5382937 , 0.7939494 ])

In [101]:
A = np.array([[1,4], [2,3],[2,10]])

c = A.mean(0)

In [102]:
Ac = A - np.outer(np.ones(3), c)
c, Ac

(array([1.66666667, 5.66666667]),
 array([[-0.66666667, -1.66666667],
        [ 0.33333333, -2.66666667],
        [ 0.33333333,  4.33333333]]))

In [106]:
C = np.eye(3) - np.ones(3)/3
Acc = C @ A
Acc

array([[-0.66666667, -1.66666667],
       [ 0.33333333, -2.66666667],
       [ 0.33333333,  4.33333333]])

In [111]:
D = np.array([[1,2,3],[4,5,6],[7,8,9]])
D2 = np.power(D, 2)
C = np.eye(3) - np.ones(3)/3
M = -0.5 * C * D2 * C
M

array([[ -0.22222222,  -0.22222222,  -0.5       ],
       [ -0.88888889,  -5.55555556,  -2.        ],
       [ -2.72222222,  -3.55555556, -18.        ]])

In [112]:
l, v = LA.eig(M)
L2 =

(array([-18.62994865+0.j,  -0.13178154+0.j,  -5.01604759+0.j]),
 array([[-0.02867887, -0.98522928, -0.01677676],
        [-0.15305455,  0.11452112, -0.96345298],
        [-0.98780151,  0.12731134,  0.26735162]]))