In [3]:
import gym
env = gym.make('CliffWalking-v0')
print("观察空间：", env.observation_space)
print("动作空间：", env.action_space)
print("状态数=%d, 动作数=%d" % (env.nS, env.nA))
print("地图数:", env.shape)

观察空间： Discrete(48)
动作空间： Discrete(4)
状态数=48, 动作数=4
地图数: (4, 12)


In [9]:
import numpy as np
actions = np.ones(env.shape, dtype=int)
actions[-1, :] = 0
actions[0:, -1] = 2
print(actions)

[[1 1 1 1 1 1 1 1 1 1 1 2]
 [1 1 1 1 1 1 1 1 1 1 1 2]
 [1 1 1 1 1 1 1 1 1 1 1 2]
 [0 0 0 0 0 0 0 0 0 0 0 2]]


In [13]:
print(env.P[0][0])

[(1.0, 0, -1, False)]


In [19]:
import scipy.optimize as opt
gamma = 1.0
p = np.zeros((env.nS, env.nA, env.nS))
r = np.zeros((env.nS, env.nA))

for state in range(env.nS - 1):
     for action in range(env.nA):
        for prob, next_state, reward, done in env.P[state][action]:
            p[state, action, next_state] += prob
            r[state, action] += (reward * prob)

c = np.ones(env.nS)
a_ub = gamma * p.reshape(-1, env.nS) - np.repeat(np.eye(env.nS), env.nA, axis=0)
b_ub = -r.reshape(-1)
a_eq = np.zeros((0, env.nS))
b_eq = np.zeros(0)
bounds = [(None, None),] * env.nS
res = opt.linprog(c, a_ub, b_ub, bounds=bounds, method='interior-point')
v = res.x
q = r + gamma * np.dot(p, v)
print(v)
print(q)

[-1.40000000e+01 -1.30000000e+01 -1.20000000e+01 -1.10000000e+01
 -1.00000000e+01 -9.00000000e+00 -8.00000000e+00 -7.00000000e+00
 -6.00000000e+00 -5.00000000e+00 -4.00000000e+00 -3.00000000e+00
 -1.30000000e+01 -1.20000000e+01 -1.10000000e+01 -1.00000000e+01
 -9.00000000e+00 -8.00000000e+00 -7.00000000e+00 -6.00000000e+00
 -5.00000000e+00 -4.00000000e+00 -3.00000000e+00 -2.00000000e+00
 -1.20000000e+01 -1.10000000e+01 -1.00000000e+01 -9.00000000e+00
 -8.00000000e+00 -7.00000000e+00 -6.00000000e+00 -5.00000000e+00
 -4.00000000e+00 -3.00000000e+00 -2.00000000e+00 -1.00000000e+00
 -1.30000000e+01 -1.20000000e+01 -1.10000000e+01 -1.00000000e+01
 -9.00000000e+00 -8.00000000e+00 -7.00000000e+00 -6.00000000e+00
 -5.00000000e+00 -4.00000000e+00 -9.99999999e-01  1.82350207e-11]
[[ -14.99999999  -13.99999999  -13.99999999  -14.99999999]
 [ -13.99999999  -13.          -13.          -14.99999999]
 [ -13.          -12.          -12.          -13.99999999]
 [ -12.          -11.          -11.       